## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("csea_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64%,Critical,5 more,2026-10-08,0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0%,Critical,33 more,Never,11
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50%,Critical,12 more,2026-10-08,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS059,KARTHIK B NAYAK,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
61,4MW24CS060,KAVYA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
62,4MW25CS400,ANAGHA K Y,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92%,Safe,✓ Met,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25%,Critical,24 more,2026-09-07,9

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------

df.head(10)

df.shape

df.dtypes

Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------

df.isnull().sum()

df.isnull().sum()[df.isnull().sum() > 0]

df[df["Last Present Date"] == "Never"]["Last Present Date"].count()

np.int64(3)

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------

df.columns = ['roll_no', 'student_name', 'subject', 'total_classes',
              'present', 'absent', 'excused', 'attendance_pct',
              'status', 'classes_needed_75_pct', 'last_present_date',
              'consecutive_absences']

print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75_pct', 'last_present_date', 'consecutive_absences']

In [6]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------

df["attendance_pct"] = df["attendance_pct"].str.replace("%", "").astype(float)

df["last_present_date"] = pd.to_datetime(
    df["last_present_date"].replace("Never", pd.NaT),
    errors="coerce"
)

display(df[["attendance_pct", "last_present_date"]].head(10))

   attendance_pct last_present_date
0            64.0        2026-10-08
1             0.0               NaT
2            83.0        2026-10-08
3           100.0        2026-10-08
4            50.0        2026-10-08
5            83.0        2026-10-08
6            83.0        2026-10-08
7            75.0        2026-10-08
8           100.0        2026-10-08
9           100.0        2026-10-08

#### Section 2: Filtering & Selection

In [7]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------

critical_students = df[df["status"] == "Critical"]

critical_students.sort_values("attendance_pct", ascending=True)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0.0,Critical,33 more,NaT,11
21,4MW24CS020,ARON OWEN D'SOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12
35,4MW24CS034,DARREN DSOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11
59,4MW24CS058,JEETHAN WELROY FERNANDES,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11
42,4MW24CS041,DHIKSHITH AITHAL KG,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-09-07,9
47,4MW24CS046,DRUSHYA K SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25.0,Critical,24 more,2026-09-07,9
20,4MW24CS019,ANVESH N ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,5,7,0,42.0,Critical,16 more,2026-09-21,6
57,4MW24CS056,HIMESH PRAKASH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-09-28,3
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-08,0
22,4MW24CS021,ARUNA,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-05,1
58,4MW24CS057,JATIN NAGESH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-05,1
55,4MW24CS054,HARSHA S RAO,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
52,4MW24CS051,GOWRISH M SHEREGARA,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
38,4MW24CS037,DEVADIGA SUHAS SURESH,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64.0,Critical,5 more,2026-10-08,0
27,4MW24CS026,ATHMIK Y ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67.0,Critical,4 more,2026-10-05,1
49,4MW24CS048,GANAVI SUSHMA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67.0,Critical,4 more,2026-10-08,0

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------

df[df["present"] == 0][["roll_no", "student_name", "consecutive_absences"]]

       roll_no              student_name  consecutive_absences
1   4MW23CS165  SUDHARSHAN BHARGAV JOSHI                    11
21  4MW24CS020         ARON OWEN D'SOUZA                    12
51  4MW24CS050          GAUTHAM G PRABHU                    12

In [9]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------

df.loc[df["status"] == "Safe"]

df.iloc[:15, 1:6]

,student_name,subject,total_classes,present,absent
0,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4
1,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11
2,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2
3,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0
4,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6
5,ADITHYA A SALIAN,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2
6,AKANKSHA G SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2
7,AMULYA B KULAL,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3
8,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0
9,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0
10,ANANYA NAYAK (UMESH NAYAK),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2
11,ANANYA NAYAK(VEERENDRA KUMAR),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2
12,ANANYA Y BANGERA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1
13,ANEESH ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3
14,ANKITHA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0

In [10]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------

df[df["consecutive_absences"] >= 5][["student_name", "status", "last_present_date"]]

                student_name    status last_present_date
1   SUDHARSHAN BHARGAV JOSHI  Critical               NaT
20          ANVESH N ACHARYA  Critical        2026-09-21
21         ARON OWEN D'SOUZA  Critical               NaT
35             DARREN DSOUZA  Critical        2026-08-31
42       DHIKSHITH AITHAL KG  Critical        2026-09-07
51          GAUTHAM G PRABHU  Critical               NaT
59  JEETHAN WELROY FERNANDES  Critical        2026-08-31
64         M NIRANJAN PRABHU  Critical        2026-09-07

### Section 3: Grouping & Aggregation

In [11]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------

df.groupby("status").agg(
    student_count = ("student_name", "count"),
    average_attendance = ("attendance_pct", "mean"),
    max_consecutive_absences = ("consecutive_absences", "max")
)

          student_count  average_attendance  max_consecutive_absences
status
Critical             19           36.263158                        12
Safe                 20           96.000000                         0
Warning              26           80.500000                         1

In [12]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------

df.loc[df["attendance_pct"] >= 90, "attendance_category"] = "Excellent"
df.loc[(df["attendance_pct"] >= 75) & (df["attendance_pct"] < 90), "attendance_category"] = "Good"
df.loc[(df["attendance_pct"] >= 60) & (df["attendance_pct"] < 75), "attendance_category"] = "Average"
df.loc[df["attendance_pct"] < 60, "attendance_category"] = "Poor"

df.groupby("attendance_category")["student_name"].count()

attendance_category
Average       3
Excellent    20
Good         26
Poor         16
Name: student_name, dtype: int64

In [13]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------

df.agg({
    "total_classes": "sum",
    "present": "sum",
    "absent": "sum"
})

total_classes    777
present          563
absent           214
dtype: int64

In [14]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------

df.groupby("status").agg(
    min_present = ("present", "min"),
    max_present = ("present", "max"),
    mean_present = ("present", "mean"),
    total_absent = ("absent", "sum")
)

          min_present  max_present  mean_present  total_absent
status
Critical            0            8      4.315789           144
Safe               11           12     11.500000            10
Warning             9           10      9.653846            60

### Section 4: Feature Engineering & Transformation

In [15]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------

df["risk_score"] = (df["absent"] * 0.4) + (df["consecutive_absences"] * 0.6)

# Display the top 10 students with the highest risk score
df.sort_values("risk_score", ascending=False).head(10)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score
21,4MW24CS020,ARON OWEN D'SOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
59,4MW24CS058,JEETHAN WELROY FERNANDES,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11,Poor,11.0
35,4MW24CS034,DARREN DSOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11,Poor,11.0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0.0,Critical,33 more,NaT,11,Poor,11.0
42,4MW24CS041,DHIKSHITH AITHAL KG,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-09-07,9,Poor,9.4
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25.0,Critical,24 more,2026-09-07,9,Poor,9.0
20,4MW24CS019,ANVESH N ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,5,7,0,42.0,Critical,16 more,2026-09-21,6,Poor,6.4
57,4MW24CS056,HIMESH PRAKASH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-09-28,3,Poor,4.2
47,4MW24CS046,DRUSHYA K SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-10-08,0,Poor,4.0

In [16]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------

df["classes_needed_numeric"] = df["classes_needed_75_pct"].str.extract(r'(\d+)').fillna(0).astype(int)

df[["classes_needed_75_pct", "classes_needed_numeric"]]

   classes_needed_75_pct  classes_needed_numeric
0                 5 more                       5
1                33 more                      33
2                  ✓ Met                       0
3                  ✓ Met                       0
4                12 more                      12
..                   ...                     ...
60                 ✓ Met                       0
61                 ✓ Met                       0
62                 ✓ Met                       0
63                 ✓ Met                       0
64               24 more                      24

[65 rows x 2 columns]

In [17]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------

df["attendance_flag"] = df["attendance_pct"].apply(
    lambda x: "Defaulter" if x < 75 else "Safe"
)

df[["student_name", "attendance_pct", "attendance_flag"]]

                student_name  attendance_pct attendance_flag
0                 ROHITH RAO            64.0       Defaulter
1   SUDHARSHAN BHARGAV JOSHI             0.0       Defaulter
2                A S ANUPAMA            83.0            Safe
3             ABHIJNA SHETTY           100.0            Safe
4                   ABHISHEK            50.0       Defaulter
..                       ...             ...             ...
60           KARTHIK B NAYAK            83.0            Safe
61                     KAVYA            83.0            Safe
62                ANAGHA K Y            83.0            Safe
63               ANVITHA B A            92.0            Safe
64         M NIRANJAN PRABHU            25.0       Defaulter

[65 rows x 3 columns]

In [18]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------

df["attendance_range"] = pd.cut(
    df["attendance_pct"],
    bins=[0, 50, 75, 90, 100],
    labels=["Critical", "Warning", "Good", "Excellent"]
)

df[["student_name", "attendance_pct", "attendance_range"]]

                student_name  attendance_pct attendance_range
0                 ROHITH RAO            64.0          Warning
1   SUDHARSHAN BHARGAV JOSHI             0.0              NaN
2                A S ANUPAMA            83.0             Good
3             ABHIJNA SHETTY           100.0        Excellent
4                   ABHISHEK            50.0         Critical
..                       ...             ...              ...
60           KARTHIK B NAYAK            83.0             Good
61                     KAVYA            83.0             Good
62                ANAGHA K Y            83.0             Good
63               ANVITHA B A            92.0        Excellent
64         M NIRANJAN PRABHU            25.0         Critical

[65 rows x 3 columns]

### Section 5: Advanced Analysis

In [19]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------

df.pivot_table(
    index="status",
    columns="attendance_category",
    values="student_name",
    aggfunc="count",
    fill_value=0
)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    16
Safe                       0         20     0     0
Warning                    0          0    26     0

In [20]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

df["base_name"] = df["student_name"].str.split().str[0]

df[df["base_name"].duplicated(keep=False)].sort_values("base_name")

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name
8,4MW24CS007,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0,Excellent,0.0,0,Safe,Excellent,ANANYA
9,4MW24CS008,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0,Excellent,0.0,0,Safe,Excellent,ANANYA
10,4MW24CS009,ANANYA NAYAK (UMESH NAYAK),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANANYA
11,4MW24CS010,ANANYA NAYAK(VEERENDRA KUMAR),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANANYA
12,4MW24CS011,ANANYA Y BANGERA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,ANANYA
16,4MW24CS015,ANUSHA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANUSHA
17,4MW24CS016,ANUSHA S BHAT,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,ANUSHA
18,4MW24CS017,ANUSHREE K,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,ANUSHREE
19,4MW24CS018,ANUSHREE P TANTRY,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0,75.0,Warning,✓ Met,2026-10-08,0,Good,1.2,0,Safe,Warning,ANUSHREE
44,4MW24CS043,DISHA (PRAKASH BANGERA),Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0,Excellent,0.4,0,Safe,Excellent,DISHA
45,4MW24CS044,DISHA (UDAY G),Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-05,1,Good,1.4,0,Safe,Good,DISHA
46,4MW24CS045,DISHA S POOJARY,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0,75.0,Warning,✓ Met,2026-10-08,0,Good,1.2,0,Safe,Warning,DISHA
50,4MW24CS049,GAUTHAM B K,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0,Good,0.8,0,Safe,Good,GAUTHAM
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0,36,Defaulter,NaN,GAUTHAM

In [21]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

Student_Details = pd.DataFrame({
    "Roll No": ["4MW24CS003", "4MW24CS059", "4MW24CS060"],
    "Branch": ["CSE", "CSE", "CSE"],
    "Semester": [5, 5, 5]
})

merged_df = pd.merge(
    df,
    Student_Details,
    left_on="roll_no",
    right_on="Roll No",
    how="inner"
)

display(merged_df)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75_pct,...,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_range,base_name,Roll No,Branch,Semester
0,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,...,0,Poor,2.4,12,Defaulter,Critical,ABHISHEK,4MW24CS003,CSE,5
1,4MW24CS059,KARTHIK B NAYAK,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,...,1,Good,1.4,0,Safe,Good,KARTHIK,4MW24CS059,CSE,5
2,4MW24CS060,KAVYA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,...,0,Good,0.8,0,Safe,Good,KAVYA,4MW24CS060,CSE,5

In [22]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

# (a) Export all Critical students
df[df["status"] == "Critical"].to_csv("critical_students.csv", index=False)

df.groupby("status").agg(
    student_count=("student_name", "count"),
    average_attendance=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max")
).to_csv("status_summary.csv")

df.sort_values("risk_score", ascending=False).head(10).to_csv(
    "top_10_risk_students.csv", index=False
)